### ISSUE TITLE
Error creating new TimeOff Event

### ISSUE THREAD

**Issue by CRiccardo** [resourceguru/api-docs#63]
I tried to use the API /v1/:subdomain/downtimes to create new Time Off Event but I always get a 422 error, and said `{"errors":"Date range not valid"}`.
Here the request json:

```
"resource_ids":1234
"booker_id":5678,
"from":"2019-05-20",
"to":"2019-05-20",
"details":"Test",
"downtime_type_id":91011,
"start_time":0,
"end_time":1440,
"timezone":"London"
```
(In the request values are examples).

And here the dump of the response:
```
HTTP/2.0 422 Unprocessable Entity
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8
Date: Thu, 16 May 2019 11:16:33 GMT
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
Vary: Accept-Encoding
Vary: Origin
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 009ae48f-a174-4c09-84d1-fef2fbb351a9
X-Runtime: 0.031809
X-Xss-Protection: 1; mode=block

{"errors":"Date range not valid"}
```

Am I missing something in the request?
Thanks in advance.

**Comment by Moristotle** [comment]
@CRiccardo did you manage to resolve the issue? 
I am experiencing a similar problem when attempting to create a new TimeOff event: Receiving a 422 (Unprocessable Entity) even though the jsonstring I'm passing is identically formatted as the example in the docs.

**Comment by KrofDrakula** [comment]
@CRiccardo In the [documentation for time off events](https://github.com/resourceguru/api-docs/blob/master/endpoints/time_off.md), it says `resource_ids` should always be specified as an array of IDs, which is why the server is rejecting your request.

For a single resource time off event, the `timezone` field should also be specified as `null`, as you cannot change the timezone of a time off event when associated with a single user.

We are aware that error responses in some cases are incorrect; we are in the process of reworking our API server, which will improve reporting errors and fix misleading error reports like these in the near future.
