### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by korishka** [resourceguru/api-docs#65]
hello, i'm having a hard time to try to get the token for my app, when trying to consume the api from a .net library. 
Using Postman the only valid token is the one with the authorization_code. I can not do that from .net code to try to call first the authorize enpoint then get the code and request the token.

Meanwhile the token that i receive with client_credentials grant type is not valid. For all the requests i do with it i get : Forbidden. 

Can you help with a solution for this. What i want to do is to build an integration with your api that will be used in our internal app. So i do not want to pass all the time user credentials, i just want to create an app and using client_id and client_secret somewhere stored to can get all time of info i need: projects and resources/bookings.

Also when trying to call from c# code the authorize endpoint in the response i get the html for login page, not the redirection page from were i could get the code to use it further,

**Comment by korishka** [comment]
Also when trying to call from c# code the authorize endpoint in the response i get the html for login page, not the redirection page from were i could get the code to use it further

**Comment by kmckelvin** [comment]
Hi korishka. To use the Resource Guru API you'll need to authenticate using OAuth2. If you want to authenticate using an email address and password, you should use the Resource Owner Password Credentials flow.

You can find further information in the [quick start section of the authentication guide](https://github.com/resourceguru/api-docs/blob/master/sections/authentication.md#quick-start-using-users-login-credentials). I suggest using an OAuth2 client library in the language of your choice rather than making the HTTP calls, as most client libraries will do some of the token management for you.
